name: Backend CI
on:
  push:
    pull_request:
      branches: [ master ]
      types: [ opened, synchronize, reopened, closed ]
jobs:
  ci:
    name: 'Backend CI'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk 
        architecture: x64 
    - name: Backend CI
      run: make backend-ci
