name: Terraform CI
on:
  push:
jobs:
  ci:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
      TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.6
    - name: Terraform fmt
      run: |
        cd terraform
        terraform fmt -check
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate -no-color
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -no-color
