name: UI CI
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, closed ]
jobs:
  ci:
    name: 'UI CI'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: UI CI
      run: make ui-ci
